#pragma once

#include <stdint.h>

/* XXX: Comment out this line for a non-test network */
//#define FBTC_TEST_NETWORK

#define FBTC_TEST_NETWORK_VERSION                            84 // autogenerated

#define FBTC_BLOCKCHAIN_DATABASE_VERSION                     uint64_t( 210 )

#define FBTC_ADDRESS_PREFIX                                  "1"
#define  CONTRACT_ADDRESS_PREFIX							"C" 
#define  SCRIPT_ID_PREFIX									"S" 
#define  MULTI_ADDRESS_PREFIX								"3"
#define FBTC_BLOCKCHAIN_SYMBOL                               "FBTC"
#define FBTC_BLOCKCHAIN_NAME                                 "Fbtc"
#define FBTC_BLOCKCHAIN_DESCRIPTION                          "Decentralized Exchange"
#define FBTC_BLOCKCHAIN_PRECISION                            100000000

#define FBTC_BLOCKCHAIN_BLOCK_INTERVAL_SEC                   uint32_t( 10 )
#define FBTC_BLOCKCHAIN_BLOCKS_PER_HOUR                      ( ( 60 * 60 ) / FBTC_BLOCKCHAIN_BLOCK_INTERVAL_SEC )
#define FBTC_BLOCKCHAIN_BLOCKS_PER_DAY                       ( 24 * FBTC_BLOCKCHAIN_BLOCKS_PER_HOUR )
#define FBTC_BLOCKCHAIN_BLOCKS_PER_YEAR                      ( 365 * FBTC_BLOCKCHAIN_BLOCKS_PER_DAY )

#define FBTC_BLOCKCHAIN_MAX_UNDO_HISTORY                     ( 3 * FBTC_BLOCKCHAIN_BLOCKS_PER_HOUR )
#define FBTC_BLOCKCHAIN_MAX_TRANSACTION_EXPIRATION_SEC       ( 2 * 24 * 60 * 60 )

#define FBTC_BLOCKCHAIN_NUM_DELEGATES                        uint32_t( 9 )
#define FBTC_BLOCKCHAIN_MAX_SLATE_SIZE                       ( FBTC_BLOCKCHAIN_NUM_DELEGATES + ( FBTC_BLOCKCHAIN_NUM_DELEGATES / 10 ) )

#define FBTC_MAX_DELEGATE_PAY_PER_BLOCK                      int64_t( 50 * FBTC_BLOCKCHAIN_PRECISION )

/**
 *  The maximum amount that can be issued for user assets.
 *
 *  10^18 / 2^63 < 1  however, to support representing all share values as a double in
 *  languages like java script, we must stay within the epsilon so
 *
 *  10^15 / 2^53 < 1 allows all values to be represented as a double or an int64
 */
#define FBTC_BLOCKCHAIN_MAX_SHARES                           ( 10000 * 1000 * int64_t( 1000 ) * 1000 * int64_t( 1000 ) )

#define FBTC_BLOCKCHAIN_MIN_NAME_SIZE                        1
#define FBTC_BLOCKCHAIN_MAX_NAME_SIZE                        63

#define FBTC_BLOCKCHAIN_MAX_SUB_SYMBOL_SIZE                  8  // characters
#define FBTC_BLOCKCHAIN_MIN_SYMBOL_SIZE                      3  // characters
#define FBTC_BLOCKCHAIN_MAX_SYMBOL_SIZE                      12 // characters

#define FBTC_BLOCKCHAIN_MIN_BURN_FEE                         FBTC_BLOCKCHAIN_PRECISION

#define FBTC_BLOCKCHAIN_MAX_MEMO_SIZE                        19 // bytes
#define FBTC_BLOCKCHAIN_EXTENDED_MEMO_SIZE                   32 // bytes
#define FBTC_BLOCKCHAIN_MAX_EXTENDED_MEMO_SIZE               ( FBTC_BLOCKCHAIN_MAX_MEMO_SIZE + FBTC_BLOCKCHAIN_EXTENDED_MEMO_SIZE )

#ifdef FBTC_TEST_NETWORK
#define FBTC_BLOCKCHAIN_VOTE_UPDATE_PERIOD_SEC               10
#else
#define FBTC_BLOCKCHAIN_VOTE_UPDATE_PERIOD_SEC               ( 60 * 60 ) // 1 hour
#endif

#define FBTC_BLOCKCHAIN_MAX_UIA_MARKET_FEE_RATE              10000 // 100%

#define FBTC_BLOCKCHAIN_MIN_FEEDS                            ( ( FBTC_BLOCKCHAIN_NUM_DELEGATES / 2 ) + 1 )

#define FBTC_BLOCKCHAIN_MAX_SHORT_APR_PCT                    uint64_t( 50 )

#ifdef FBTC_TEST_NETWORK
#define FBTC_BLOCKCHAIN_MAX_SHORT_PERIOD_SEC                 ( 2 * 60 * 60 ) // 2 hours
#else
#define FBTC_BLOCKCHAIN_MAX_SHORT_PERIOD_SEC                 ( 30 * 24 * 60 * 60 ) // 1 month
#endif

#define FBTC_BLOCKCHAIN_MCALL_D2C_NUMERATOR                  1
#define FBTC_BLOCKCHAIN_MCALL_D2C_DENOMINATOR                2

#define FBTC_BLOCKCHAIN_MIN_YIELD_PERIOD_SEC                 ( 24 * 60 * 60 ) // 24 hours
#define FBTC_BLOCKCHAIN_MAX_YIELD_PERIOD_SEC                 ( 365 * FBTC_BLOCKCHAIN_MIN_YIELD_PERIOD_SEC ) // 1 year

// TODO: This stuff only matters for propagation throttling; should go somewhere else
#define FBTC_BLOCKCHAIN_DEFAULT_RELAY_FEE                    1000 // XTS
#define FBTC_BLOCKCHAIN_MAX_TRX_PER_SECOND                   100 // (10)
#define FBTC_BLOCKCHAIN_MAX_PENDING_QUEUE_SIZE               10000 // (FBTC_BLOCKCHAIN_MAX_TRX_PER_SECOND * FBTC_BLOCKCHAIN_BLOCK_INTERVAL_SEC)
